package MethodAndFunctions;

import  java.util.Scanner;
import java.util.Random;

class Game{
  public int ComputerInput  , UserGuess  ,  no_of_guess =0;

  //constructor for Genrating random number  -------------
  public Game(){
    Random random = new Random();
    ComputerInput = random.nextInt(10);
  }

  // method to take guess from user -------------------------
  public void UserInput(int num){
    UserGuess = num;
  }

  // method to check weather users guess is right or wrong ----------------
    /* this while method will check weather the number chosen by user is equal to number
     generated by computer is right or wrong like wise ti will update the value of no_of_guess
     every time and return true or false as result */

  public boolean IsCorrectNumber(){
    if(UserGuess > ComputerInput){
      System.out.println("You have chosen Bigger No");
      no_of_guess = no_of_guess + 1;
      return false;
    }
    else  if(UserGuess < ComputerInput){
      System.out.println("You have Chosen Smaller number");
      no_of_guess = no_of_guess + 1;
      return  false;
    }
    else {
      System.out.println("Your Guess is Correct");
      no_of_guess = no_of_guess + 1;
      System.out.println("Number of Guess required : "+no_of_guess);
      return true;
    }
  }
}
public class GuessTheNumber {
  public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);
    System.out.println("WELCOME TO GUESS THE NUMBER GAME ! ");

        /* by creating object player we have called Game constructor and -------------
         the Game() constructor contain definition to generate a random number
         so random number will be generated  as we know when object is created Constructor is called*/
    Game player = new Game();

    /// this will take input from user as guess ---------------------
    System.out.println("Guess the Number from 0 to 10 : ");
    player.UserInput(sc.nextInt());

        /* this loop will run util the condition become true -------------------
        if IsCorrectGuess function return false then it will call function UserInput() until result gets true
        and according to condition update the value of no_of_guess
          */
    while(!player.IsCorrectNumber()){
      System.out.println("Guess the Number Again");
      player.UserInput(sc.nextInt());
    }
  }
}
